// ============================================================
// PROGRESS//OS — core domain types
// ============================================================

export type TopicStatus = 'not_started' | 'learning' | 'practicing' | 'revising' | 'mastered';

export interface Topic {
  id: string;
  subjectId: string;
  name: string;
  status: TopicStatus;
  confidence: number; // 0-100
  difficulty: 1 | 2 | 3 | 4 | 5;
  timeSpentMin: number;
  questionsSolved: number;
  lastRevised: string | null; // ISO date
  revisionIntervalDays: number;
  createdAt: string;
  // Sprint 1 additive fields (optional so existing rows without them still type-check)
  completionPct?: number; // 0-100
  notes?: string;
  nextRevision?: string | null; // ISO date
  revisionCount?: number;
  mistakes?: string;
  formulae?: string;
}

export interface Subject {
  id: string;
  name: string;
  color: string; // hex accent for charts
  createdAt: string;
  // Sprint 1 additive fields: marks a subject as generated by the Academic
  // Syllabus Generator (vs. one the user created manually), so it can be
  // safely identified and replaced if the user later changes their goal.
  syllabusGoal?: AcademicGoalType | null;
  autoGenerated?: boolean;
}

export interface StudySession {
  id: string;
  subjectId: string;
  topicId: string | null;
  date: string; // ISO date (yyyy-mm-dd)
  startedAt: string; // ISO datetime
  durationMin: number;
  questionsSolved: number;
  focusRating: number; // 1-5
  noPhone: boolean;
  notes?: string;
}

export type TaskCategory = 'study' | 'health' | 'mind' | 'personal' | 'work';
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';

export interface Task {
  id: string;
  title: string;
  category: TaskCategory;
  priority: TaskPriority;
  estimatedMin: number;
  deadline: string | null; // ISO date
  date: string; // the day it's scheduled for, ISO date
  done: boolean;
  doneAt: string | null;
  pomodoroCount: number;
  progress: number; // 0-100
  createdAt: string;
}

export type XPSourceType =
  | 'wake_on_time'
  | 'study_session'
  | 'workout'
  | 'reading'
  | 'meditation'
  | 'no_phone_study'
  | 'revision'
  | 'mock_test'
  | 'perfect_day'
  | 'task_complete'
  | 'manual';

export interface XPEvent {
  id: string;
  amount: number;
  source: XPSourceType;
  label: string;
  date: string; // ISO date
  timestamp: string; // ISO datetime
}

export interface DailyLog {
  id: string; // == date, ISO date, one per day
  date: string;
  wokeOnTime: boolean | null;
  sleepHours: number | null;
  bedTimeConsistent: boolean | null;
  workoutDone: boolean;
  readingMin: number;
  meditationMin: number;
  screenTimeMin: number | null;
  procrastinationRating: number | null; // 1-5, 5 = high procrastination
  lateStart: boolean;
  tasksCompleted: number;
  tasksMissed: number;
  studyMin: number;
  mood: number | null; // 1-5
  energy: number | null; // 1-5
  journalNotes: string;
  reflection: string;
  wins: string;
  failures: string;
  lessons: string;
  tomorrowFocus: string;
}

export interface CharacterStats {
  discipline: number;
  consistency: number;
  focus: number;
  productivity: number;
  energy: number;
  knowledge: number;
  health: number;
  confidence: number;
}

export interface StatSnapshot extends CharacterStats {
  id: string;
  date: string; // ISO date
}

export type GoalPeriod = 'daily' | 'weekly' | 'monthly' | 'yearly';

export interface Goal {
  id: string;
  title: string;
  period: GoalPeriod;
  targetValue: number;
  currentValue: number;
  unit: string;
  createdAt: string;
  deadline: string | null;
  completed: boolean;
}

export type AchievementId =
  | 'first_session'
  | 'hours_10'
  | 'hours_100'
  | 'hours_500'
  | 'hours_1000'
  | 'streak_7'
  | 'streak_30'
  | 'streak_100'
  | 'no_missed_week'
  | 'early_bird'
  | 'night_owl'
  | 'bookworm'
  | 'perfect_week'
  | 'perfect_month'
  | 'level_10'
  | 'level_25'
  | 'level_50'
  | 'level_100'
  | 'mock_master'
  | 'revision_streak';

export interface Achievement {
  id: AchievementId;
  title: string;
  description: string;
  icon: string; // lucide icon name
  unlockedAt: string | null;
  tier: 'bronze' | 'silver' | 'gold' | 'platinum';
}

export interface AppSettings {
  id: 'settings';
  xpMultiplier: number;
  pomodoroMin: number;
  breakMin: number;
  soundEffects: boolean;
  animations: boolean;
  dailyStudyGoalMin: number;
  levelScalingFactor: number; // exponent for level formula
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  // Sprint 2 additive fields — optional so settings rows created before
  // Sprint 2 still type-check; defaults are supplied by
  // lib/planner.ts#getEnergyProfile rather than a DB migration.
  energyMorning?: EnergyLevel;
  energyAfternoon?: EnergyLevel;
  energyEvening?: EnergyLevel;
  energyNight?: EnergyLevel;
}

// ============================================================
// SPRINT 1 — Academic Intelligence
// ============================================================

export type AcademicGoalType =
  | 'jee_main'
  | 'jee_advanced'
  | 'neet'
  | 'class_11'
  | 'class_12'
  | 'custom';

export interface AcademicProfile {
  id: 'academic';
  onboarded: boolean;
  goal: AcademicGoalType | null;
  customGoalName: string | null;
  examDate: string | null; // ISO date (yyyy-mm-dd)
  createdAt: string;
}

export type ChapterStatus = 'not_started' | 'in_progress' | 'revising' | 'mastered';

/**
 * @deprecated Sprint 1 originally stored syllabus chapters in a separate
 * table. Fix 1 replaced this with real Subject/Topic rows so the existing
 * Study Tracker renders them natively. This type (and its Dexie table) is
 * kept only so any earlier-generated data isn't silently deleted; nothing
 * new writes to it.
 */
export interface AcademicChapter {
  id: string;
  goal: AcademicGoalType;
  subjectName: string; // e.g. 'Physics' | 'Chemistry' | 'Mathematics' | 'Biology'
  chapterName: string;
  completionPct: number; // 0-100
  revisionCount: number;
  practicePct: number; // 0-100
  confidenceRating: number; // 1-5
  lastStudied: string | null; // ISO date
  nextRevision: string | null; // ISO date
  estimatedHours: number;
  notes: string;
  status: ChapterStatus;
  questionCount: number;
  createdAt: string;
}

export interface TopicRevision {
  id: string;
  topicId: string;
  date: string; // ISO date
  createdAt: string;
}

// ============================================================
// SPRINT 2 — Smart Slot Planner
// ============================================================

export type EnergyLevel = 'low' | 'medium' | 'high';
export type TimeOfDay = 'morning' | 'afternoon' | 'evening' | 'night';

export type SlotTaskType = 'new_learning' | 'practice' | 'revision' | 'mock_test' | 'assignment' | 'other';

export type SlotStatus = 'planned' | 'in_progress' | 'completed' | 'skipped' | 'rescheduled';
// Note: 'missed' is intentionally NOT a stored status — it's derived at
// read-time (see lib/planner.ts#getEffectiveSlotStatus) from a 'planned'
// slot whose end time has passed. Nothing writes 'missed' to the DB, so a
// slot rescheduled after being missed just becomes 'planned' again with no
// lingering penalty record for the discipline score to pick up.

export interface PlannerSlot {
  id: string;
  date: string; // ISO date (yyyy-mm-dd)
  startTime: string; // 'HH:mm', 24h
  endTime: string; // 'HH:mm', 24h
  subjectId: string | null;
  topicId: string | null;
  taskType: SlotTaskType;
  priority: TaskPriority;
  estimatedDuration: number; // minutes
  energyRequirement: EnergyLevel;
  status: SlotStatus;
  completionPct: number; // 0-100
  notes: string;
  autoGenerated: boolean; // created by "Generate Today's Plan"
  rescheduledFromId: string | null; // points at the slot this replaced, if any
  createdAt: string;
}
